name: Clang-Format

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04 # https://github.com/actions/runner-images/issues/10636
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0
      - name: Ensure git safe directory
        run: |
          git config --global --add safe.directory $(pwd)
      - name: Install clang-format-18
        run: |
          sudo apt update
          sudo apt install clang-format-18
      - name: Run clang-format
        run: |
          bash ./.github/scripts/clang-format.sh `which clang-format-18`
